-- ALTER TABLE element ADD tags TEXT;
DROP TABLE IF EXISTS game;
DROP TABLE IF EXISTS game_and_element;
DROP TABLE IF EXISTS game_tag;
DROP TABLE IF EXISTS game_link;

CREATE TABLE game (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  comment TEXT,
  
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE game_link (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  comment TEXT,
  game_id INTEGER NOT NULL REFERENCES game (id) ON DELETE CASCADE,
  author_id INTEGER NOT NULL REFERENCES user (id) ON DELETE SET NULL
);

CREATE TABLE game_tag (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  comment TEXT,
  game_id INTEGER NOT NULL REFERENCES game (id) ON DELETE CASCADE,
  author_id INTEGER NOT NULL REFERENCES user (id) ON DELETE SET NULL
);

CREATE TABLE game_and_element (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id INTEGER REFERENCES game (id) ON DELETE CASCADE,
  element_id INTEGER REFERENCES element (id) ON DELETE RESTRICT,
  author_id INTEGER NOT NULL REFERENCES user (id)
);